import type { UserRoleDefinition } from '../types';

export const ROLE_TEMPLATES: Record<string, UserRoleDefinition> = {
  JUNIOR_REVIEWER: {
    roleId: 'junior_reviewer',
    roleName: 'Junior Reviewer',
    description: 'Can approve disbursements as a junior reviewer',
    permissions: {
      viewDistributions: false,
      viewCollections: false,
      initiateDisbursements: false,
      approveDisbursements: true,
      viewReports: false,
      manageRoles: false,
      configureSettings: false,
    },
    turnkeyUserTagTemplate: 'role:junior_reviewer',
    requiresPolicyApproval: false,
  },
  SENIOR_REVIEWER: {
    roleId: 'senior_reviewer',
    roleName: 'Senior Reviewer',
    description: 'Can approve disbursements as a senior reviewer',
    permissions: {
      viewDistributions: false,
      viewCollections: false,
      initiateDisbursements: false,
      approveDisbursements: true,
      viewReports: false,
      manageRoles: false,
      configureSettings: false,
    },
    turnkeyUserTagTemplate: 'role:senior_reviewer',
    requiresPolicyApproval: true,
  },
  COMPLIANCE_OFFICER: {
    roleId: 'compliance_officer',
    roleName: 'Compliance Officer',
    description: 'Can view distribution and collection vaults with reporting capabilities',
    permissions: {
      viewDistributions: true,
      viewCollections: true,
      initiateDisbursements: false,
      approveDisbursements: false,
      viewReports: true,
      manageRoles: false,
      configureSettings: false,
    },
    turnkeyUserTagTemplate: 'role:compliance_officer',
    requiresPolicyApproval: true,
  },
  ADMINISTRATOR: {
    roleId: 'administrator',
    roleName: 'Administrator',
    description: 'Full system access including role management and configuration',
    permissions: {
      viewDistributions: true,
      viewCollections: true,
      initiateDisbursements: true,
      approveDisbursements: true,
      viewReports: true,
      manageRoles: true,
      configureSettings: true,
    },
    turnkeyUserTagTemplate: 'role:administrator',
    requiresPolicyApproval: true,
    maxUsers: 3,
  },
  READ_ONLY_AUDITOR: {
    roleId: 'read_only_auditor',
    roleName: 'Read-Only Auditor',
    description: 'View-only access for audit purposes',
    permissions: {
      viewDistributions: true,
      viewCollections: true,
      initiateDisbursements: false,
      approveDisbursements: false,
      viewReports: true,
      manageRoles: false,
      configureSettings: false,
    },
    turnkeyUserTagTemplate: 'role:read_only_auditor',
    requiresPolicyApproval: false,
  },
};
